// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  What the window the front end is drawing into turned out to be.
	 * 
	 *  Asked once at startup. The window has already been dressed by then, so this
	 *  reports what happened rather than causing it.
	 */
	windowChrome: () => typedError<Chrome, Failure>(__TAURI_INVOKE("window_chrome")),
	/**
	 *  Opens the platform's own folder picker.
	 * 
	 *  Separate from adding the folder, so that a front end that already knows the
	 *  path, from a drag and drop for instance, does not have to open a dialog to
	 *  use it.
	 */
	chooseFolder: () => typedError<string | null, Failure>(__TAURI_INVOKE("choose_folder")),
	/**
	 *  Opens the platform's own file picker, filtered to subtitle files.
	 * 
	 *  What the attach action in the import sheet opens, for a film whose subtitle
	 *  was not found beside it.
	 */
	chooseSubtitle: () => typedError<string | null, Failure>(__TAURI_INVOKE("choose_subtitle")),
	/**
	 *  The folders that a set of dropped paths stand for.
	 * 
	 *  Dropping a film means the folder it is in, since that is where its subtitles
	 *  are and where the next film will be put. The front end adds what comes back
	 *  the same way it adds a folder that was picked.
	 */
	foldersForPaths: (paths: string[]) => typedError<string[], Failure>(__TAURI_INVOKE("folders_for_paths", { paths })),
	/**
	 *  Starts watching a folder and reads what is in it.
	 * 
	 *  Returns as soon as the folder has been recorded. Reading it happens behind
	 *  this and reports itself through the scan events, because a folder of a
	 *  thousand films takes a few seconds and the folder should appear in the list
	 *  straight away.
	 */
	addFolder: (path: string) => typedError<FolderView, Failure>(__TAURI_INVOKE("add_folder", { path })),
	/**
	 *  Gives a subtitle file to a film because somebody said so.
	 * 
	 *  The amber row in the import sheet. Reading and parsing the file is real work
	 *  on a real thread rather than on the one answering commands, and it waits
	 *  behind any scan that is running, so it must not hold up the runtime while it
	 *  does.
	 */
	attachSubtitle: (filmId: Id, path: string) => typedError<TrackView, Failure>(__TAURI_INVOKE("attach_subtitle", { filmId, path })),
	/**  Stops watching a folder and forgets what was found in it. */
	removeFolder: (id: Id) => typedError<boolean, Failure>(__TAURI_INVOKE("remove_folder", { id })),
	/**  The folders being watched, with how many films each holds. */
	listFolders: () => typedError<FolderView[], Failure>(__TAURI_INVOKE("list_folders")),
	/**  Every film in the library, with its subtitle tracks and where it was left. */
	listLibrary: () => typedError<FilmView[], Failure>(__TAURI_INVOKE("list_library")),
	/**
	 *  The films with no frame captured from them yet.
	 * 
	 *  A poster is wanted when the film has none, when the file it names is not
	 *  there any more, and when the film's own file has changed since the frame was
	 *  taken. The last of those needs nothing stored to compare against: the name a
	 *  poster is filed under is derived from the film's path and modification time,
	 *  so a film whose row names a different file is a film whose frame is stale.
	 */
	postersWanted: () => typedError<PosterWanted[], Failure>(__TAURI_INVOKE("posters_wanted")),
	/**
	 *  Records the frame captured from a film, and what was learnt taking it.
	 * 
	 *  The encoding and the colours are the front end's work, because the frame is
	 *  already decoded there and sending four megabytes of pixels across to have
	 *  them squeezed here would cost more than it saved. What arrives is a WebP of
	 *  a few tens of kilobytes.
	 * 
	 *  The running time comes with it: opening the file is the only way to find out
	 *  how long a film is, and the capture has just done that. Without it a partly
	 *  watched film has a position and no fraction to draw it as.
	 */
	savePoster: (filmId: Id, image: number[], accent: {
	/**  The colour the film's glow and its accent are drawn in. */
	primary: string,
	/**  The second colour of the pair, which the ambient wash uses. */
	pair: string,
} | null, durationMs: number | null) => typedError<FilmView, Failure>(__TAURI_INVOKE("save_poster", { filmId, image, accent, durationMs })),
	/**
	 *  Reads every watched folder again.
	 * 
	 *  Cheap when nothing has moved: an unchanged folder is one stat per file and
	 *  no parsing at all. Returns straight away, like adding a folder does.
	 */
	rescan: () => typedError<null, Failure>(__TAURI_INVOKE("rescan")),
	/**
	 *  Where the scan that is running has got to, for a window that opened part way
	 *  through one and has not seen any events yet.
	 */
	scanProgress: () => typedError<{
	folderId: Id,
	stage: StageView,
	filesSeen: number,
	filmsFound: number,
	subtitlesFound: number,
	filmsPaired: number,
	subtitlesToRead: number,
	subtitlesRead: number,
	cuesIndexed: number,
	/**  How much of the reading is done, from zero to one. */
	fractionRead: number,
} | null, Failure>(__TAURI_INVOKE("scan_progress")),
	/**  Whether a scan is running at all. */
	isScanning: () => typedError<boolean, Failure>(__TAURI_INVOKE("is_scanning")),
};

/** Events */
export const events = {
	scanFailed: makeEvent<ScanFailed>("scan-failed"),
	scanFinished: makeEvent<ScanFinished>("scan-finished"),
	scanProgressed: makeEvent<ScanProgressed>("scan-progressed"),
};

/* Types */
/**
 *  The colour pair taken from a film's own frame.
 * 
 *  Kept in one column as two hex triples separated by a space, because nothing
 *  ever queries one colour without the other and a second column would only be
 *  a second thing to keep in step.
 */
export type AccentView = {
	/**  The colour the film's glow and its accent are drawn in. */
	primary: string,
	/**  The second colour of the pair, which the ambient wash uses. */
	pair: string,
};

/**  What the front end needs to know about the window it is drawing into. */
export type Chrome = {
	/**
	 *  The desktop shows through behind the window, so the surfaces drawn on
	 *  top of it are the translucent ones. False everywhere the window is
	 *  opaque, where the same surfaces would be washed out over nothing.
	 */
	backdrop: boolean,
};

/**
 *  Something that went wrong, said in a way a person can act on.
 * 
 *  Errors do not cross the boundary as types. A front end cannot do anything
 *  useful with a variant name, and every failure here comes down to a sentence
 *  to put on the screen.
 */
export type Failure = {
	message: string,
};

/**  What the parser had to work around in one file, as sentences. */
export type FileWarnings = {
	path: string,
	warnings: string[],
};

/**  A film and everything the library screen needs to draw it. */
export type FilmView = {
	id: Id,
	folderId: Id,
	path: string,
	title: string,
	year: number | null,
	durationMs: number | null,
	posterPath: string | null,
	accent: AccentView | null,
	/**  The file is not where it was. The film is kept anyway. */
	missing: boolean,
	tracks: TrackView[],
	position: PositionView | null,
};

/**  A folder the library is a view onto. */
export type FolderView = {
	id: Id,
	path: string,
	addedAt: Millis,
	films: number,
	/**  Whether changes to it are being noticed as they happen. */
	watching: boolean,
};

/**
 *  A row number on its way to the front end.
 * 
 *  SQLite hands out sixty-four bit identifiers, and JavaScript cannot hold
 *  every value one of those can. It goes across as a plain number rather than
 *  as a bigint, because a library would have to reach nine thousand million
 *  films before an identifier stopped being exact, and a bigint would make
 *  every comparison and every URL on every screen more awkward for a limit
 *  nobody will meet.
 */
export type Id = number;

/**  How sure the pairing between a film and a subtitle file is. */
export type MatchKindView = "exact" | "approximate" | "by-hand";

/**
 *  A moment, in milliseconds since the epoch. Wide for the same reason as
 *  [`Id`], and narrowed for the same one.
 */
export type Millis = number;

/**  Where a film was left. */
export type PositionView = {
	positionMs: number,
	durationMs: number | null,
	finished: boolean,
	updatedAt: Millis,
	/**  How far through, from zero to one, where the running time is known. */
	progress: number | null,
};

/**  A film with no frame captured from it yet. */
export type PosterWanted = {
	id: Id,
	path: string,
};

/**
 *  A scan that stopped part way through, and why.
 * 
 *  Whatever it had already written is still there: batches are committed
 *  whole, so this means some files went unread, not that any were read badly.
 */
export type ScanFailed = Failure;

/**  Every folder a scan covered, once all of them have finished. */
export type ScanFinished = ScanSummary[];

/**  How far along a scan is. */
export type ScanProgressed = {
	folderId: Id,
	stage: StageView,
	filesSeen: number,
	filmsFound: number,
	subtitlesFound: number,
	filmsPaired: number,
	subtitlesToRead: number,
	subtitlesRead: number,
	cuesIndexed: number,
	/**  How much of the reading is done, from zero to one. */
	fractionRead: number,
};

/**  What a scan found, once it has finished. */
export type ScanSummary = {
	folderId: Id,
	filmsFound: number,
	subtitlesFound: number,
	filmsPaired: number,
	subtitlesRead: number,
	cuesIndexed: number,
	filmsMissing: number,
	/**
	 *  Subtitle files belonging to no film, which the import sheet offers to
	 *  attach by hand.
	 */
	unpairedSubtitles: string[],
	/**  Films with no subtitle, which get no transcript and no search. */
	filmsWithoutSubtitles: string[],
	/**  Files that could not be read at all. */
	unreadable: string[],
	/**  Files the parser had to work around, and what was wrong with each. */
	warnings: FileWarnings[],
};

/**  Which step of a scan is running. */
export type StageView = "discovering" | "pairing" | "indexing" | "finished";

/**  A subtitle file paired with a film. */
export type TrackView = {
	id: Id,
	path: string,
	language: string | null,
	forced: boolean,
	hearingImpaired: boolean,
	matchKind: MatchKindView,
	cueCount: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

