// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  What the window the front end is drawing into turned out to be.
	 * 
	 *  Asked once at startup. The window has already been dressed by then, so this
	 *  reports what happened rather than causing it.
	 */
	windowChrome: () => typedError<Chrome, Failure>(__TAURI_INVOKE("window_chrome")),
	/**
	 *  Opens the platform's own folder picker.
	 * 
	 *  Separate from adding the folder, so that a front end that already knows the
	 *  path, from a drag and drop for instance, does not have to open a dialog to
	 *  use it.
	 */
	chooseFolder: () => typedError<string | null, Failure>(__TAURI_INVOKE("choose_folder")),
	/**
	 *  Opens the platform's own file picker, filtered to subtitle files.
	 * 
	 *  What the attach action in the import sheet opens, for a film whose subtitle
	 *  was not found beside it.
	 */
	chooseSubtitle: () => typedError<string | null, Failure>(__TAURI_INVOKE("choose_subtitle")),
	/**
	 *  The folders that a set of dropped paths stand for.
	 * 
	 *  Dropping a film means the folder it is in, since that is where its subtitles
	 *  are and where the next film will be put. The front end adds what comes back
	 *  the same way it adds a folder that was picked.
	 */
	foldersForPaths: (paths: string[]) => typedError<string[], Failure>(__TAURI_INVOKE("folders_for_paths", { paths })),
	/**
	 *  Starts watching a folder and reads what is in it.
	 * 
	 *  Returns as soon as the folder has been recorded. Reading it happens behind
	 *  this and reports itself through the scan events, because a folder of a
	 *  thousand films takes a few seconds and the folder should appear in the list
	 *  straight away.
	 */
	addFolder: (path: string) => typedError<FolderView, Failure>(__TAURI_INVOKE("add_folder", { path })),
	/**
	 *  Gives a subtitle file to a film because somebody said so.
	 * 
	 *  The amber row in the import sheet. Reading and parsing the file is real work
	 *  on a real thread rather than on the one answering commands, and it waits
	 *  behind any scan that is running, so it must not hold up the runtime while it
	 *  does.
	 */
	attachSubtitle: (filmId: Id, path: string) => typedError<TrackView, Failure>(__TAURI_INVOKE("attach_subtitle", { filmId, path })),
	/**  Stops watching a folder and forgets what was found in it. */
	removeFolder: (id: Id) => typedError<boolean, Failure>(__TAURI_INVOKE("remove_folder", { id })),
	/**  The folders being watched, with how many films each holds. */
	listFolders: () => typedError<FolderView[], Failure>(__TAURI_INVOKE("list_folders")),
	/**  Every film in the library, with its subtitle tracks and where it was left. */
	listLibrary: () => typedError<FilmView[], Failure>(__TAURI_INVOKE("list_library")),
	/**
	 *  The films to carry on with, most recently watched first.
	 * 
	 *  A separate command rather than a filter over the library, because the order
	 *  is by when each was last watched and the row shows a handful rather than
	 *  everything. Films whose files have gone are included and marked missing,
	 *  since an unplugged drive is exactly the case positions outlive their files
	 *  for.
	 */
	continueWatching: (limit: number) => typedError<FilmView[], Failure>(__TAURI_INVOKE("continue_watching", { limit })),
	/**
	 *  Every line of dialogue in one subtitle track, in playback order.
	 * 
	 *  The whole track at once rather than a window around the current moment. A
	 *  five thousand cue film is a few hundred kilobytes, it is read once when the
	 *  player opens, and having all of it in memory is what lets the active line be
	 *  found by a binary search on every frame instead of by asking across the
	 *  boundary sixty times a second.
	 */
	trackCues: (trackId: Id) => typedError<CueView[], Failure>(__TAURI_INVOKE("track_cues", { trackId })),
	/**
	 *  Records how a subtitle track's timings line up with its film.
	 * 
	 *  Written when somebody has settled on a value rather than while they are
	 *  arriving at one. Every intermediate step of a nudge would be this write and
	 *  a re-read of the whole track behind it, so the player shows the steps itself
	 *  and calls this once at the end.
	 * 
	 *  The film comes back rather than the track alone, because a correction
	 *  changes what the cues of that film are and the library screen holds the
	 *  film. What comes back is read from the database, so a value outside the
	 *  bounds the core enforces returns as the value that was actually kept.
	 */
	setTrackCorrection: (trackId: Id, correction: CorrectionView) => typedError<FilmView, Failure>(__TAURI_INVOKE("set_track_correction", { trackId, correction })),
	/**
	 *  Records which subtitle track a film is watched with.
	 * 
	 *  A track to read it with, or nothing at all, which is a decision in its own
	 *  right and is why turning subtitles off is written down rather than simply
	 *  not choosing. The state a film starts in, where nobody has chosen, is not
	 *  something this can write: it is what the row already says, and going back to
	 *  it is not one of the answers the menu offers.
	 * 
	 *  The film comes back rather than an acknowledgement, because the choice
	 *  changes which cues that film has and the library screen holds the film.
	 */
	setFilmTrack: (filmId: Id, trackId: number | null) => typedError<FilmView, Failure>(__TAURI_INVOKE("set_film_track", { filmId, trackId })),
	/**
	 *  Finds a line of dialogue anywhere in the library, or in one film.
	 * 
	 *  Called on a keystroke, so the work happens on a thread of its own rather
	 *  than on the runtime that answers every other command. What comes back is
	 *  grouped by film and ranked, and the query itself is treated as words rather
	 *  than as index syntax, so nothing anybody types is an error.
	 */
	searchDialogue: (query: string, filmId: number | null) => typedError<SearchView, Failure>(__TAURI_INVOKE("search_dialogue", { query, filmId })),
	/**
	 *  What has been searched for before, most recent first.
	 * 
	 *  What the palette offers before anybody has typed anything.
	 */
	recentSearches: () => typedError<string[], Failure>(__TAURI_INVOKE("recent_searches")),
	/**
	 *  Keeps a search, because it found something worth opening.
	 * 
	 *  Returns the list it made rather than nothing, so the palette shows what was
	 *  written rather than what it assumed would be.
	 */
	rememberSearch: (query: string) => typedError<string[], Failure>(__TAURI_INVOKE("remember_search", { query })),
	/**  Forgets every search that has been made. */
	forgetSearches: () => typedError<null, Failure>(__TAURI_INVOKE("forget_searches")),
	/**
	 *  Records how far through a film somebody is.
	 * 
	 *  Called on a throttle while playing and once on the way out, so it is one row
	 *  replaced and nothing else. The running time comes with it because the player
	 *  is the thing that knows it: a film whose poster was never captured has no
	 *  duration stored, and without one the library cannot draw how far through it
	 *  is.
	 */
	savePosition: (filmId: Id, positionMs: number, durationMs: number | null, finished: boolean) => typedError<null, Failure>(__TAURI_INVOKE("save_position", { filmId, positionMs, durationMs, finished })),
	/**
	 *  The films with no frame captured from them yet.
	 * 
	 *  A poster is wanted when the film has none, when the file it names is not
	 *  there any more, and when the film's own file has changed since the frame was
	 *  taken. The last of those needs nothing stored to compare against: the name a
	 *  poster is filed under is derived from the film's path and modification time,
	 *  so a film whose row names a different file is a film whose frame is stale.
	 */
	postersWanted: () => typedError<PosterWanted[], Failure>(__TAURI_INVOKE("posters_wanted")),
	/**
	 *  Records the frame captured from a film, and what was learnt taking it.
	 * 
	 *  The encoding and the colours are the front end's work, because the frame is
	 *  already decoded there and sending four megabytes of pixels across to have
	 *  them squeezed here would cost more than it saved. What arrives is a WebP of
	 *  a few tens of kilobytes.
	 * 
	 *  The running time comes with it: opening the file is the only way to find out
	 *  how long a film is, and the capture has just done that. Without it a partly
	 *  watched film has a position and no fraction to draw it as.
	 */
	savePoster: (filmId: Id, image: number[], accent: {
	/**  The colour the film's glow and its accent are drawn in. */
	primary: string,
	/**  The second colour of the pair, which the ambient wash uses. */
	pair: string,
} | null, durationMs: number | null) => typedError<FilmView, Failure>(__TAURI_INVOKE("save_poster", { filmId, image, accent, durationMs })),
	/**
	 *  Every preference that has been set, by key.
	 * 
	 *  The whole lot in one call rather than a call per control. There are a few
	 *  dozen of them, they are read once when the window opens, and the settings
	 *  screen is not the only thing that wants them: the player, the transcript and
	 *  the window itself are all drawn from these before anybody has opened
	 *  settings at all.
	 */
	readPreferences: () => typedError<PreferenceView[], Failure>(__TAURI_INVOKE("read_preferences")),
	/**
	 *  Records one preference.
	 * 
	 *  One row replaced, which is why this is not batched or thrown away on a
	 *  timer: a control that has been changed has been changed, and a window closed
	 *  a moment later should still open the way it was left.
	 */
	writePreference: (key: string, value: string) => typedError<null, Failure>(__TAURI_INVOKE("write_preference", { key, value })),
	/**
	 *  Builds the search index again, and then reads the folders afresh.
	 * 
	 *  For a library whose search has stopped agreeing with its dialogue, which a
	 *  scan that was interrupted or a file copied between machines can leave
	 *  behind. Nothing is reparsed and no pairing is lost: the index is built from
	 *  the cues already stored.
	 * 
	 *  Returns straight away and reports itself through the scan events, like the
	 *  scans it ends with.
	 */
	rebuildIndex: () => typedError<null, Failure>(__TAURI_INVOKE("rebuild_index")),
	/**
	 *  Reads every watched folder again.
	 * 
	 *  Cheap when nothing has moved: an unchanged folder is one stat per file and
	 *  no parsing at all. Returns straight away, like adding a folder does.
	 */
	rescan: () => typedError<null, Failure>(__TAURI_INVOKE("rescan")),
	/**
	 *  Where the scan that is running has got to, for a window that opened part way
	 *  through one and has not seen any events yet.
	 */
	scanProgress: () => typedError<{
	folderId: Id,
	stage: StageView,
	filesSeen: number,
	filmsFound: number,
	subtitlesFound: number,
	filmsPaired: number,
	subtitlesToRead: number,
	subtitlesRead: number,
	filmsToRead: number,
	filmsRead: number,
	cuesIndexed: number,
	/**  How much of the reading is done, from zero to one. */
	fractionRead: number,
} | null, Failure>(__TAURI_INVOKE("scan_progress")),
	/**  Whether a scan is running at all. */
	isScanning: () => typedError<boolean, Failure>(__TAURI_INVOKE("is_scanning")),
};

/** Events */
export const events = {
	scanFailed: makeEvent<ScanFailed>("scan-failed"),
	scanFinished: makeEvent<ScanFinished>("scan-finished"),
	scanProgressed: makeEvent<ScanProgressed>("scan-progressed"),
};

/* Types */
/**
 *  The colour pair taken from a film's own frame.
 * 
 *  Kept in one column as two hex triples separated by a space, because nothing
 *  ever queries one colour without the other and a second column would only be
 *  a second thing to keep in step.
 */
export type AccentView = {
	/**  The colour the film's glow and its accent are drawn in. */
	primary: string,
	/**  The second colour of the pair, which the ambient wash uses. */
	pair: string,
};

/**  What the front end needs to know about the window it is drawing into. */
export type Chrome = {
	/**
	 *  The desktop shows through behind the window, so the surfaces drawn on
	 *  top of it are the translucent ones. False everywhere the window is
	 *  opaque, where the same surfaces would be washed out over nothing.
	 */
	backdrop: boolean,
	/**
	 *  Whether turning hardware decoding off would do anything here. Only the
	 *  Windows webview takes a switch for it; everywhere else the decision
	 *  belongs to the platform, and the settings screen leaves out a control it
	 *  would not be telling the truth about.
	 */
	switchableDecoding: boolean,
};

/**
 *  How a track's timings relate to the film it is paired with.
 * 
 *  One shape rather than two loose numbers, because neither means anything
 *  without the other and both travel together in each direction: out on the
 *  track, and back in when somebody has settled on a value.
 */
export type CorrectionView = {
	/**  How far the whole track is moved, in milliseconds. Negative is earlier. */
	offsetMs: number,
	/**
	 *  What the track is stretched by, for a file written against a release at
	 *  a different framerate. One for almost every track.
	 */
	rate: number,
};

/**  One of the nine places a cue can ask to be drawn. */
export type CuePositionView = "top-left" | "top-centre" | "top-right" | "middle-left" | "middle-centre" | "middle-right" | "bottom-left" | "bottom-centre" | "bottom-right";

/**
 *  One line of dialogue, as the player and the transcript want it.
 * 
 *  Deliberately flat and deliberately small. A film of five thousand cues
 *  crosses the boundary in one go and is then searched sixty times a second, so
 *  every field here is a number or a string the renderer uses directly, with
 *  nothing to unpack on the other side.
 */
export type CueView = {
	/**  Position in the track, counted from one in playback order. */
	index: number,
	startMs: number,
	endMs: number,
	/**  The dialogue as plain text. A cue of several lines keeps its breaks. */
	text: string,
	/**  Where the file asked for the cue to be drawn, if it asked at all. */
	position: CuePositionView | null,
};

/**  One line of dialogue that matched. */
export type DialogueHit = {
	/**  Where in the film it is said, which is where selecting it opens the film. */
	startMs: number,
	/**  The line around the match, split at the matched words. */
	snippet: SnippetPart[],
};

/**
 *  Something that went wrong, said in a way a person can act on.
 * 
 *  Errors do not cross the boundary as types. A front end cannot do anything
 *  useful with a variant name, and every failure here comes down to a sentence
 *  to put on the screen.
 */
export type Failure = {
	message: string,
};

/**  What the parser had to work around in one file, as sentences. */
export type FileWarnings = {
	path: string,
	warnings: string[],
};

/**  The lines one film had to offer, best first. */
export type FilmMatches = {
	filmId: Id,
	/**
	 *  Carried rather than looked up on the other side, so that a film indexed
	 *  since the library screen last read itself still has a name in the
	 *  palette.
	 */
	title: string,
	year: number | null,
	hits: DialogueHit[],
	/**
	 *  Matches in this film that were not returned, because the film had
	 *  reached its share of the results.
	 */
	withheld: number,
};

/**  A film and everything the library screen needs to draw it. */
export type FilmView = {
	id: Id,
	folderId: Id,
	path: string,
	title: string,
	year: number | null,
	durationMs: number | null,
	posterPath: string | null,
	accent: AccentView | null,
	/**  The file is not where it was. The film is kept anyway. */
	missing: boolean,
	tracks: TrackView[],
	/**
	 *  The track this film is watched with, where somebody has said which.
	 * 
	 *  Null covers two different things, and the flag beside it is what tells
	 *  them apart: nobody has chosen, in which case the front end picks one by
	 *  its rule, or subtitles have been turned off and none is wanted.
	 */
	chosenTrackId: Id | null,
	subtitlesOff: boolean,
	position: PositionView | null,
};

/**  A folder the library is a view onto. */
export type FolderView = {
	id: Id,
	path: string,
	addedAt: Millis,
	films: number,
	/**  Whether changes to it are being noticed as they happen. */
	watching: boolean,
};

/**
 *  A row number on its way to the front end.
 * 
 *  SQLite hands out sixty-four bit identifiers, and JavaScript cannot hold
 *  every value one of those can. It goes across as a plain number rather than
 *  as a bigint, because a library would have to reach nine thousand million
 *  films before an identifier stopped being exact, and a bigint would make
 *  every comparison and every URL on every screen more awkward for a limit
 *  nobody will meet.
 */
export type Id = number;

/**  How sure the pairing between a film and a subtitle file is. */
export type MatchKindView = "exact" | "approximate" | "by-hand";

/**
 *  A moment, in milliseconds since the epoch. Wide for the same reason as
 *  [`Id`], and narrowed for the same one.
 */
export type Millis = number;

/**  Where a film was left. */
export type PositionView = {
	positionMs: number,
	durationMs: number | null,
	finished: boolean,
	updatedAt: Millis,
	/**  How far through, from zero to one, where the running time is known. */
	progress: number | null,
};

/**  A film with no frame captured from it yet. */
export type PosterWanted = {
	id: Id,
	path: string,
};

/**
 *  One preference, as it is stored.
 * 
 *  Both halves are text, and what the text means belongs to the settings
 *  screen. Sending them across as they are keeps a control that is added there
 *  from being a change here as well, and it is why adding one is a change to
 *  one file rather than to a command, a type and a screen.
 */
export type PreferenceView = {
	key: string,
	value: string,
};

/**
 *  A scan that stopped part way through, and why.
 * 
 *  Whatever it had already written is still there: batches are committed
 *  whole, so this means some files went unread, not that any were read badly.
 */
export type ScanFailed = Failure;

/**  Every folder a scan covered, once all of them have finished. */
export type ScanFinished = ScanSummary[];

/**  How far along a scan is. */
export type ScanProgressed = {
	folderId: Id,
	stage: StageView,
	filesSeen: number,
	filmsFound: number,
	subtitlesFound: number,
	filmsPaired: number,
	subtitlesToRead: number,
	subtitlesRead: number,
	filmsToRead: number,
	filmsRead: number,
	cuesIndexed: number,
	/**  How much of the reading is done, from zero to one. */
	fractionRead: number,
};

/**  What a scan found, once it has finished. */
export type ScanSummary = {
	folderId: Id,
	filmsFound: number,
	subtitlesFound: number,
	filmsPaired: number,
	subtitlesRead: number,
	cuesIndexed: number,
	filmsMissing: number,
	/**
	 *  Subtitle files belonging to no film, which the import sheet offers to
	 *  attach by hand.
	 */
	unpairedSubtitles: string[],
	/**  Films with no subtitle, which get no transcript and no search. */
	filmsWithoutSubtitles: string[],
	/**  Files that could not be read at all. */
	unreadable: string[],
	/**  Files the parser had to work around, and what was wrong with each. */
	warnings: FileWarnings[],
};

/**  Everything one search found, grouped by the film it was found in. */
export type SearchView = {
	/**  Films in the order their best line ranked. */
	films: FilmMatches[],
	/**  How many lines are being shown, which the palette says out loud. */
	shown: number,
	/**
	 *  Whether the search stopped at the limit rather than running out of
	 *  matches, so the palette can say "the first hundred" honestly.
	 */
	truncated: boolean,
	/**
	 *  Whether these are the best matches or simply the first ones. A search
	 *  matching half the library gives up ranking rather than keeping somebody
	 *  waiting for an order they typed straight past.
	 */
	ranked: boolean,
};

/**
 *  A stretch of a snippet, and whether it is one of the words searched for.
 * 
 *  The index marks matches with two control characters, and splitting on them
 *  happens here rather than on the other side. A front end handed the marked
 *  string would have to find them again to draw the highlight, and a line of
 *  dialogue that happened to contain one would be drawn wrongly. Across the
 *  boundary the shape says what it means.
 */
export type SnippetPart = {
	text: string,
	matched: boolean,
};

/**  Which step of a scan is running. */
export type StageView = "discovering" | "pairing" | "indexing" | "finished";

/**
 *  What a track is made of, which is what decides whether it can be read.
 * 
 *  The codec itself does not cross the boundary. Everything a screen has to say
 *  about a track comes down to these three cases, and sending the name instead
 *  would mean the front end keeping its own list of which codecs are which.
 */
export type TrackFormView = 
/**  Dialogue, which becomes a transcript and lines in the search index. */
"text" | 
/**
 *  Images of dialogue, as Blu-ray discs and DVDs carry. Naming them is as
 *  far as this goes: reading them would mean optical character
 *  recognition, a large dependency and an accuracy figure nothing else
 *  here has to apologise for.
 */
"pictures" | 
/**  Something this build has no name for. */
"unrecognised";

/**  Whether a track is a file beside the film or a stream inside it. */
export type TrackOriginView = "sidecar" | "stream";

/**  A subtitle track of a film, whether beside it or inside it. */
export type TrackView = {
	id: Id,
	path: string,
	origin: TrackOriginView,
	/**
	 *  The number the container knows the track by, which is what tells two
	 *  tracks of one film apart when they say the same thing about themselves.
	 *  Zero for a subtitle file.
	 */
	streamNumber: number,
	/**  Whether the dialogue in this track can be read. */
	form: TrackFormView,
	language: string | null,
	forced: boolean,
	hearingImpaired: boolean,
	matchKind: MatchKindView,
	cueCount: number,
	/**
	 *  What the timings have been put through to match the film.
	 * 
	 *  Carried so that the sync control opens on the value in force rather than
	 *  on nothing, and so that the player knows what the cues it was handed
	 *  have already had done to them.
	 */
	correction: CorrectionView,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

