// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  What the window the front end is drawing into turned out to be.
	 * 
	 *  Asked once at startup. The window has already been dressed by then, so this
	 *  reports what happened rather than causing it.
	 */
	windowChrome: () => typedError<Chrome, Failure>(__TAURI_INVOKE("window_chrome")),
	/**
	 *  Opens the platform's own folder picker.
	 * 
	 *  Separate from adding the folder, so that a front end that already knows the
	 *  path, from a drag and drop for instance, does not have to open a dialog to
	 *  use it.
	 */
	chooseFolder: () => typedError<string | null, Failure>(__TAURI_INVOKE("choose_folder")),
	/**
	 *  Opens the platform's own file picker, filtered to subtitle files.
	 * 
	 *  What the attach action in the import sheet opens, for a film whose subtitle
	 *  was not found beside it.
	 */
	chooseSubtitle: () => typedError<string | null, Failure>(__TAURI_INVOKE("choose_subtitle")),
	/**
	 *  The folders that a set of dropped paths stand for.
	 * 
	 *  Dropping a film means the folder it is in, since that is where its subtitles
	 *  are and where the next film will be put. The front end adds what comes back
	 *  the same way it adds a folder that was picked.
	 */
	foldersForPaths: (paths: string[]) => typedError<string[], Failure>(__TAURI_INVOKE("folders_for_paths", { paths })),
	/**
	 *  Starts watching a folder and reads what is in it.
	 * 
	 *  Returns as soon as the folder has been recorded. Reading it happens behind
	 *  this and reports itself through the scan events, because a folder of a
	 *  thousand films takes a few seconds and the folder should appear in the list
	 *  straight away.
	 */
	addFolder: (path: string) => typedError<FolderView, Failure>(__TAURI_INVOKE("add_folder", { path })),
	/**
	 *  Gives a subtitle file to a film because somebody said so.
	 * 
	 *  The amber row in the import sheet. Reading and parsing the file is real work
	 *  on a real thread rather than on the one answering commands, and it waits
	 *  behind any scan that is running, so it must not hold up the runtime while it
	 *  does.
	 */
	attachSubtitle: (filmId: Id, path: string) => typedError<TrackView, Failure>(__TAURI_INVOKE("attach_subtitle", { filmId, path })),
	/**  Stops watching a folder and forgets what was found in it. */
	removeFolder: (id: Id) => typedError<boolean, Failure>(__TAURI_INVOKE("remove_folder", { id })),
	/**  The folders being watched, with how many films each holds. */
	listFolders: () => typedError<FolderView[], Failure>(__TAURI_INVOKE("list_folders")),
	/**  Every film in the library, with its subtitle tracks and where it was left. */
	listLibrary: () => typedError<FilmView[], Failure>(__TAURI_INVOKE("list_library")),
	/**
	 *  The films to carry on with, most recently watched first.
	 * 
	 *  A separate command rather than a filter over the library, because the order
	 *  is by when each was last watched and the row shows a handful rather than
	 *  everything. Films whose files have gone are included and marked missing,
	 *  since an unplugged drive is exactly the case positions outlive their files
	 *  for.
	 */
	continueWatching: (limit: number) => typedError<FilmView[], Failure>(__TAURI_INVOKE("continue_watching", { limit })),
	/**
	 *  Every line of dialogue in one subtitle track, in playback order.
	 * 
	 *  The whole track at once rather than a window around the current moment. A
	 *  five thousand cue film is a few hundred kilobytes, it is read once when the
	 *  player opens, and having all of it in memory is what lets the active line be
	 *  found by a binary search on every frame instead of by asking across the
	 *  boundary sixty times a second.
	 */
	trackCues: (trackId: Id) => typedError<CueView[], Failure>(__TAURI_INVOKE("track_cues", { trackId })),
	/**
	 *  Records how a subtitle track's timings line up with its film.
	 * 
	 *  Written when somebody has settled on a value rather than while they are
	 *  arriving at one. Every intermediate step of a nudge would be this write and
	 *  a re-read of the whole track behind it, so the player shows the steps itself
	 *  and calls this once at the end.
	 * 
	 *  The film comes back rather than the track alone, because a correction
	 *  changes what the cues of that film are and the library screen holds the
	 *  film. What comes back is read from the database, so a value outside the
	 *  bounds the core enforces returns as the value that was actually kept.
	 */
	setTrackCorrection: (trackId: Id, correction: CorrectionView) => typedError<FilmView, Failure>(__TAURI_INVOKE("set_track_correction", { trackId, correction })),
	/**
	 *  Works out how a subtitle track's timings line up with its film, by listening
	 *  to the film.
	 * 
	 *  The number somebody would otherwise arrive at by ear, measured instead. It
	 *  is asked for rather than done on its own, because decoding the audio of
	 *  every film in a library would cost minutes of a machine that is doing
	 *  something else and would mostly correct files that are already right.
	 * 
	 *  Real work on a thread of its own, since reading a two hour film takes
	 *  several seconds and the film is expected to keep playing throughout. What
	 *  comes back covers every ending, including the ones where nothing was
	 *  written.
	 */
	alignTrack: (trackId: Id) => typedError<AlignmentView, Failure>(__TAURI_INVOKE("align_track", { trackId })),
	/**
	 *  Stops the alignment that is running.
	 * 
	 *  Leaves the track as it was. Nothing is written until a measurement has been
	 *  made and believed, and a reading that stops makes no measurement.
	 */
	cancelAlignment: () => typedError<null, Failure>(__TAURI_INVOKE("cancel_alignment")),
	/**
	 *  Where the alignment that is running has got to, for a screen that has not
	 *  seen any events yet.
	 */
	alignmentProgress: () => typedError<{
	trackId: Id,
	stage: AlignStageView,
	/**  How much of the film has been read, from zero to one. */
	fraction: number,
} | null, Failure>(__TAURI_INVOKE("alignment_progress")),
	/**
	 *  Records which subtitle track a film is watched with.
	 * 
	 *  A track to read it with, or nothing at all, which is a decision in its own
	 *  right and is why turning subtitles off is written down rather than simply
	 *  not choosing. The state a film starts in, where nobody has chosen, is not
	 *  something this can write: it is what the row already says, and going back to
	 *  it is not one of the answers the menu offers.
	 * 
	 *  The film comes back rather than an acknowledgement, because the choice
	 *  changes which cues that film has and the library screen holds the film.
	 */
	setFilmTrack: (filmId: Id, trackId: number | null) => typedError<FilmView, Failure>(__TAURI_INVOKE("set_film_track", { filmId, trackId })),
	/**
	 *  Records how far through a film somebody is.
	 * 
	 *  Called on a throttle while playing and once on the way out, so it is one row
	 *  replaced and nothing else. The running time comes with it because the player
	 *  is the thing that knows it: a film whose poster was never captured has no
	 *  duration stored, and without one the library cannot draw how far through it
	 *  is.
	 */
	savePosition: (filmId: Id, positionMs: number, durationMs: number | null, finished: boolean) => typedError<null, Failure>(__TAURI_INVOKE("save_position", { filmId, positionMs, durationMs, finished })),
	/**
	 *  Shows a film where it sits, in the platform's own file manager.
	 * 
	 *  A film is named by its identifier rather than by its path, so the only files
	 *  this can be asked about are files the library already holds. The path is
	 *  then put through the same rule the protocols answer to, which is what makes
	 *  a row pointing somewhere it should not a refusal rather than a window onto
	 *  somebody's documents.
	 */
	showInFolder: (filmId: Id) => typedError<null, Failure>(__TAURI_INVOKE("show_in_folder", { filmId })),
	/**
	 *  The films with no poster drawn for them yet.
	 * 
	 *  A poster is wanted when the film has none, when the file it names is not
	 *  there any more, when the film's own file has changed since it was drawn, and
	 *  when the cover it was drawn from is no longer where the cover comes from.
	 *  None of those needs anything stored to compare against: the name a poster is
	 *  filed under is derived from all three, so a film whose row names a different
	 *  file is a film whose poster is stale.
	 * 
	 *  Each film also says whether there is an image to draw it from. Where there
	 *  is, the front end asks for those bytes; where there is not, it opens the
	 *  film and takes a frame, which is the expensive answer and the last one.
	 */
	postersWanted: () => typedError<PosterWanted[], Failure>(__TAURI_INVOKE("posters_wanted")),
	/**
	 *  The cover image a film's poster is to be drawn from.
	 * 
	 *  One command whichever of the two sources it came from, so the front end has
	 *  one thing to do with an image and no idea where it was: the scan settled
	 *  that, and the row says so. What comes back is a picture as it sits on the
	 *  disk, tens of kilobytes of it, which the same worker crops, encodes and
	 *  takes the colours from as it does a frame.
	 */
	coverImage: (filmId: Id) => typedError<number[], Failure>(__TAURI_INVOKE("cover_image", { filmId })),
	/**
	 *  Records the poster drawn for a film, and what was learnt drawing it.
	 * 
	 *  The encoding and the colours are the front end's work, because the frame is
	 *  already decoded there and sending four megabytes of pixels across to have
	 *  them squeezed here would cost more than it saved. What arrives is a WebP of
	 *  a few tens of kilobytes.
	 * 
	 *  The running time comes with it where there is one: opening the file is the
	 *  only way to find out how long a film is, and a capture has just done that.
	 *  A poster drawn from a cover image says nothing about it, since nothing
	 *  opened the film, and the player fills it in the first time anybody watches.
	 */
	savePoster: (filmId: Id, image: number[], accent: {
	/**  The colour the film's glow and its accent are drawn in. */
	primary: string,
	/**  The second colour of the pair, which the ambient wash uses. */
	pair: string,
} | null, durationMs: number | null) => typedError<FilmView, Failure>(__TAURI_INVOKE("save_poster", { filmId, image, accent, durationMs })),
	/**
	 *  Every preference that has been set, by key.
	 * 
	 *  The whole lot in one call rather than a call per control. There are a few
	 *  dozen of them, they are read once when the window opens, and the settings
	 *  screen is not the only thing that wants them: the player and the window
	 *  itself are both drawn from these before anybody has opened settings at
	 *  all.
	 */
	readPreferences: () => typedError<PreferenceView[], Failure>(__TAURI_INVOKE("read_preferences")),
	/**
	 *  Records one preference.
	 * 
	 *  One row replaced, which is why this is not batched or thrown away on a
	 *  timer: a control that has been changed has been changed, and a window closed
	 *  a moment later should still open the way it was left.
	 */
	writePreference: (key: string, value: string) => typedError<null, Failure>(__TAURI_INVOKE("write_preference", { key, value })),
	/**
	 *  Forgets preferences the application no longer has anything to do with.
	 * 
	 *  Which keys those are is the front end's to say, because the front end is
	 *  where the table of settings lives and duplicating it here would be a second
	 *  list to keep in step. This end only does as it is told, and a key that was
	 *  not there was already forgotten.
	 */
	forgetPreferences: (keys: string[]) => typedError<null, Failure>(__TAURI_INVOKE("forget_preferences", { keys })),
	/**
	 *  Reads every watched folder again.
	 * 
	 *  Cheap when nothing has moved: an unchanged folder is one stat per file and
	 *  no parsing at all. Returns straight away, like adding a folder does.
	 */
	rescan: () => typedError<null, Failure>(__TAURI_INVOKE("rescan")),
	/**
	 *  Where the scan that is running has got to, for a window that opened part way
	 *  through one and has not seen any events yet.
	 */
	scanProgress: () => typedError<{
	folderId: Id,
	stage: StageView,
	filesSeen: number,
	filmsFound: number,
	subtitlesFound: number,
	filmsPaired: number,
	subtitlesToRead: number,
	subtitlesRead: number,
	filmsToRead: number,
	filmsRead: number,
	cuesIndexed: number,
	/**  How much of the reading is done, from zero to one. */
	fractionRead: number,
} | null, Failure>(__TAURI_INVOKE("scan_progress")),
	/**  Whether a scan is running at all. */
	isScanning: () => typedError<boolean, Failure>(__TAURI_INVOKE("is_scanning")),
};

/** Events */
export const events = {
	alignProgressed: makeEvent<AlignProgressed>("align-progressed"),
	scanFailed: makeEvent<ScanFailed>("scan-failed"),
	scanFinished: makeEvent<ScanFinished>("scan-finished"),
	scanProgressed: makeEvent<ScanProgressed>("scan-progressed"),
};

/* Types */
/**
 *  The colour pair taken from a film's own frame.
 * 
 *  Kept in one column as two hex triples separated by a space, because nothing
 *  ever queries one colour without the other and a second column would only be
 *  a second thing to keep in step.
 */
export type AccentView = {
	/**  The colour the film's glow and its accent are drawn in. */
	primary: string,
	/**  The second colour of the pair, which the ambient wash uses. */
	pair: string,
};

/**
 *  How far along an alignment is.
 * 
 *  Reading the film is nearly all of the time an alignment takes, and it is the
 *  part that can be stopped, so it is the part that reports itself. The
 *  correlation is under a second and says only that it has started.
 */
export type AlignProgressed = {
	trackId: Id,
	stage: AlignStageView,
	/**  How much of the film has been read, from zero to one. */
	fraction: number,
};

/**  Which step of an alignment is running. */
export type AlignStageView = 
/**  Decoding the film's audio to find where the talking is. */
"reading" | 
/**  Matching that against where the subtitle says the talking is. */
"correlating";

/**
 *  How an attempt to line a subtitle track up with its film ended.
 * 
 *  One shape covering every ending, so that the front end matches on this and
 *  has no case of its own to invent. Only the first of them writes anything.
 *  The rest leave the track exactly as it was, with the nudge keys still where
 *  they were, which is the point: an answer nobody can check is worse than no
 *  answer, and each of these says plainly which it is.
 */
export type AlignmentView = 
/**  The track has been moved to where the dialogue in the film actually is. */
{ outcome: "aligned"; correction: CorrectionView; 
/**  What was in force beforehand, so that it can be put back. */
previous: CorrectionView; 
/**  How sure the measurement was, from nothing to certain. */
confidence: number; 
/**  How the lines land now. */
landing: LandingView; 
/**
 *  How they landed before, which is what makes the figure above mean
 *  something.
 */
asWritten: LandingView; 
/**
 *  What the track was measured against, since the two answers are not
 *  of the same quality and the figures above read differently for each.
 */
reference: ReferenceView } | 
/**
 *  The track carries too few lines to be correlated with anything.
 * 
 *  What a forced or signs-only track looks like. Settled from the count on
 *  the track's own row, before any audio is read.
 */
{ outcome: "too-few-cues"; cues: number; 
/**  How many it would have taken. */
wanted: number } | 
/**  The film has no soundtrack, so there is nothing to measure against. */
{ outcome: "no-audio" } | 
/**
 *  The soundtrack is in a codec this build has no decoder for.
 * 
 *  The same boundary the README states about video, in the same terms:
 *  nothing is broken and trying again will not help.
 */
{ outcome: "unsupported"; 
/**  What the codec is called, where it is one anybody has a name for. */
codec: string | null } | 
/**
 *  A measurement was made and is not worth acting on.
 * 
 *  What a subtitle belonging to a different film produces. The correction
 *  it would have written comes back with it, since somebody who wants it
 *  can still type it in, but nothing has been written.
 */
{ outcome: "uncertain"; correction: CorrectionView; confidence: number; 
/**  How sure it would have had to be. */
wanted: number; landing: LandingView; asWritten: LandingView } | 
/**
 *  A measurement was made, believed, and would not have helped.
 * 
 *  The correlation can be perfectly clear about a lag and still be answering
 *  the wrong question, since the confidence beside it is read off the same
 *  peak and cannot see past it. This is the outcome where the answer was put
 *  to the film itself and did not put more lines on the talking than the
 *  file already does, or did not put enough of them there to be worth
 *  writing over somebody's library.
 */
{ outcome: "no-better"; correction: CorrectionView; landing: LandingView; asWritten: LandingView; 
/**  The share of lines a measurement has to land to be written. */
wanted: number } | 
/**  The film could not be opened, or nothing in it could be made sense of. */
{ outcome: "unreadable"; message: string } | 
/**  Somebody asked for it to stop, and it stopped. */
{ outcome: "stopped" };

/**  One of a film's sound tracks. */
export type AudioView = {
	codec: string,
	/**  What the channel count amounts to, said the way somebody would say it. */
	layout: string | null,
	language: string | null,
	/**  The track the film suggests, which is the one that will be heard. */
	default: boolean,
};

/**  What the front end needs to know about the window it is drawing into. */
export type Chrome = {
	/**
	 *  The desktop shows through behind the window, so the surfaces drawn on
	 *  top of it are the translucent ones. False everywhere the window is
	 *  opaque, where the same surfaces would be washed out over nothing.
	 */
	backdrop: boolean,
	/**
	 *  Whether turning hardware decoding off would do anything here. Only the
	 *  Windows webview takes a switch for it; everywhere else the decision
	 *  belongs to the platform, and the settings screen leaves out a control it
	 *  would not be telling the truth about.
	 */
	switchableDecoding: boolean,
};

/**
 *  How a track's timings relate to the film it is paired with.
 * 
 *  One shape rather than two loose numbers, because neither means anything
 *  without the other and both travel together in each direction: out on the
 *  track, and back in when somebody has settled on a value.
 */
export type CorrectionView = {
	/**  How far the whole track is moved, in milliseconds. Negative is earlier. */
	offsetMs: number,
	/**
	 *  What the track is stretched by, for a file written against a release at
	 *  a different framerate. One for almost every track.
	 */
	rate: number,
};

/**  One of the nine places a cue can ask to be drawn. */
export type CuePositionView = "top-left" | "top-centre" | "top-right" | "middle-left" | "middle-centre" | "middle-right" | "bottom-left" | "bottom-centre" | "bottom-right";

/**
 *  One line of dialogue, as the player wants it.
 * 
 *  Deliberately flat and deliberately small. A film of five thousand cues
 *  crosses the boundary in one go and is then searched sixty times a second, so
 *  every field here is a number or a string the renderer uses directly, with
 *  nothing to unpack on the other side.
 */
export type CueView = {
	/**  Position in the track, counted from one in playback order. */
	index: number,
	startMs: number,
	endMs: number,
	/**  The dialogue as plain text. A cue of several lines keeps its breaks. */
	text: string,
	/**  Where the file asked for the cue to be drawn, if it asked at all. */
	position: CuePositionView | null,
};

/**
 *  Something that went wrong, said in a way a person can act on.
 * 
 *  Errors do not cross the boundary as types. A front end cannot do anything
 *  useful with a variant name, and every failure here comes down to a sentence
 *  to put on the screen.
 */
export type Failure = {
	message: string,
};

/**  What the parser had to work around in one file, as sentences. */
export type FileWarnings = {
	path: string,
	warnings: string[],
};

/**  A film and everything the library screen needs to draw it. */
export type FilmView = {
	id: Id,
	folderId: Id,
	path: string,
	/**
	 *  The row this film sits on, read from where it is filed on disk.
	 * 
	 *  Worked out here rather than on the other side, so that the front end
	 *  groups by a value it was given instead of taking paths apart with a
	 *  separator it would have to guess at.
	 */
	shelf: ShelfView,
	title: string,
	year: number | null,
	/**
	 *  When the film was first recorded, which is as near as this gets to when
	 *  somebody acquired it. A file's own timestamps are not used: copying a
	 *  library onto a new drive rewrites those and would date every film to the
	 *  afternoon of the copy.
	 */
	addedAt: Millis,
	durationMs: number | null,
	posterPath: string | null,
	accent: AccentView | null,
	/**  The file is not where it was. The film is kept anyway. */
	missing: boolean,
	/**
	 *  What the file turned out to be, once a scan has looked at it.
	 * 
	 *  One group rather than a dozen loose fields, because none of it means
	 *  anything on its own and all of it arrives together. Absent for a film
	 *  recorded before this build described such things, until the next scan.
	 */
	details: MediaView | null,
	tracks: TrackView[],
	/**
	 *  The track this film is watched with, where somebody has said which.
	 * 
	 *  Null covers two different things, and the flag beside it is what tells
	 *  them apart: nobody has chosen, in which case the front end picks one by
	 *  its rule, or subtitles have been turned off and none is wanted.
	 */
	chosenTrackId: Id | null,
	subtitlesOff: boolean,
	position: PositionView | null,
};

/**  A folder the library is a view onto. */
export type FolderView = {
	id: Id,
	path: string,
	addedAt: Millis,
	films: number,
	/**  Whether changes to it are being noticed as they happen. */
	watching: boolean,
};

/**
 *  A row number on its way to the front end.
 * 
 *  SQLite hands out sixty-four bit identifiers, and JavaScript cannot hold
 *  every value one of those can. It goes across as a plain number rather than
 *  as a bigint, because a library would have to reach nine thousand million
 *  films before an identifier stopped being exact, and a bigint would make
 *  every comparison and every URL on every screen more awkward for a limit
 *  nobody will meet.
 */
export type Id = number;

/**
 *  How many of a track's lines arrive when somebody starts talking.
 * 
 *  The one figure in an alignment that was not read off the correlation that
 *  produced the answer, which is what makes it worth showing. It is quoted
 *  twice, once for the file as it stands and once for what a measurement would
 *  make of it, because neither number means much alone: no film puts every line
 *  on a voice, and what a person wants to know is whether this would be better.
 */
export type LandingView = {
	/**  The share of lines landing on the start of an utterance, none to all. */
	fraction: number,
	/**  How far the middle line falls from the nearest one, in milliseconds. */
	medianMs: number,
	/**
	 *  How many lines were measured. Nought where there was nothing to measure,
	 *  which is what tells an empty answer from a bad one.
	 */
	examined: number,
};

/**  How sure the pairing between a film and a subtitle file is. */
export type MatchKindView = "exact" | "approximate" | "by-hand";

/**
 *  What a film's file is, as the sheet describes it.
 * 
 *  Everything inside was read once, when the film was scanned, and is held on
 *  the row from then on. A fact the file did not state is absent rather than
 *  nought, so a screen can leave out what it does not know instead of printing
 *  a number nobody wrote.
 */
export type MediaView = {
	/**
	 *  What the file is, which is known for every film since it comes from the
	 *  name rather than from anything inside.
	 */
	container: string,
	sizeBytes: number,
	/**
	 *  Bits a second across the whole film, from its size and its running time.
	 * 
	 *  An average, and labelled as one wherever it is shown: no encode of
	 *  anything worth watching holds one rate from beginning to end.
	 */
	averageBitrate: number | null,
	video: VideoView | null,
	audio: AudioView[],
};

/**
 *  A moment, in milliseconds since the epoch. Wide for the same reason as
 *  [`Id`], and narrowed for the same one.
 */
export type Millis = number;

/**  Where a film was left. */
export type PositionView = {
	positionMs: number,
	durationMs: number | null,
	finished: boolean,
	updatedAt: Millis,
	/**  How far through, from zero to one, where the running time is known. */
	progress: number | null,
};

/**  A film with no poster drawn for it yet. */
export type PosterWanted = {
	id: Id,
	path: string,
	/**
	 *  Whether there is an image on the disk to draw it from, either inside the
	 *  film or beside it. Where there is not, a frame has to be taken from the
	 *  picture, which means opening the film and decoding it.
	 */
	cover: boolean,
};

/**
 *  One preference, as it is stored.
 * 
 *  Both halves are text, and what the text means belongs to the settings
 *  screen. Sending them across as they are keeps a control that is added there
 *  from being a change here as well, and it is why adding one is a change to
 *  one file rather than to a command, a type and a screen.
 */
export type PreferenceView = {
	key: string,
	value: string,
};

/**
 *  What a measurement was made against.
 * 
 *  There are two things in a film that say where its dialogue falls, and they
 *  are not equally good. The soundtrack is always there and has to be decoded
 *  and read, which takes seconds and is only ever an estimate of where somebody
 *  is talking. Another text subtitle track of the same film is authored timings
 *  on both sides, needs no decoder, and is accurate to the bin, but most films
 *  do not carry one.
 * 
 *  Which of the two answered is worth saying, because it is the difference
 *  between a measurement to the millisecond and one to the fraction of a second,
 *  and somebody reading the sentence should know which they have been handed.
 */
export type ReferenceView = 
/**  The talking in the film's own soundtrack. */
{ against: "speech" } | 
/**  Another text subtitle track of the same film. */
{ against: "track"; 
/**  What language it is in, where the file says. */
language: string | null; 
/**
 *  Whether it came from inside the film rather than from beside it. A
 *  track inside the film was muxed against these exact frames, which is
 *  why it is preferred and why it is worth naming.
 */
inside: boolean };

/**
 *  A scan that stopped part way through, and why.
 * 
 *  Whatever it had already written is still there: batches are committed
 *  whole, so this means some files went unread, not that any were read badly.
 */
export type ScanFailed = Failure;

/**  Every folder a scan covered, once all of them have finished. */
export type ScanFinished = ScanSummary[];

/**  How far along a scan is. */
export type ScanProgressed = {
	folderId: Id,
	stage: StageView,
	filesSeen: number,
	filmsFound: number,
	subtitlesFound: number,
	filmsPaired: number,
	subtitlesToRead: number,
	subtitlesRead: number,
	filmsToRead: number,
	filmsRead: number,
	cuesIndexed: number,
	/**  How much of the reading is done, from zero to one. */
	fractionRead: number,
};

/**  What a scan found, once it has finished. */
export type ScanSummary = {
	folderId: Id,
	filmsFound: number,
	subtitlesFound: number,
	filmsPaired: number,
	subtitlesRead: number,
	cuesIndexed: number,
	filmsMissing: number,
	/**
	 *  Subtitle files belonging to no film, which the import sheet offers to
	 *  attach by hand.
	 */
	unpairedSubtitles: string[],
	/**  Films with no subtitle, which the sheet marks as such. */
	filmsWithoutSubtitles: string[],
	/**  Files that could not be read at all. */
	unreadable: string[],
	/**  Files the parser had to work around, and what was wrong with each. */
	warnings: FileWarnings[],
};

/**
 *  The row a film sits on, which is the folder somebody filed it in.
 * 
 *  The name is the heading and the path is what sits beside it, since two
 *  watched folders can each hold a directory called the same thing and the name
 *  alone would not say which row is which.
 */
export type ShelfView = {
	name: string,
	path: string,
};

/**  Which step of a scan is running. */
export type StageView = "discovering" | "pairing" | "indexing" | "finished";

/**
 *  What a track is made of, which is what decides whether it can be read.
 * 
 *  The codec itself does not cross the boundary. Everything a screen has to say
 *  about a track comes down to these three cases, and sending the name instead
 *  would mean the front end keeping its own list of which codecs are which.
 */
export type TrackFormView = 
/**  Dialogue, which is what the player draws and steps between. */
"text" | 
/**
 *  Images of dialogue, as Blu-ray discs and DVDs carry. Naming them is as
 *  far as this goes: reading them would mean optical character
 *  recognition, a large dependency and an accuracy figure nothing else
 *  here has to apologise for.
 */
"pictures" | 
/**  Something this build has no name for. */
"unrecognised";

/**  Whether a track is a file beside the film or a stream inside it. */
export type TrackOriginView = "sidecar" | "stream";

/**  A subtitle track of a film, whether beside it or inside it. */
export type TrackView = {
	id: Id,
	path: string,
	origin: TrackOriginView,
	/**
	 *  The number the container knows the track by, which is what tells two
	 *  tracks of one film apart when they say the same thing about themselves.
	 *  Zero for a subtitle file.
	 */
	streamNumber: number,
	/**  Whether the dialogue in this track can be read. */
	form: TrackFormView,
	language: string | null,
	forced: boolean,
	hearingImpaired: boolean,
	matchKind: MatchKindView,
	cueCount: number,
	/**
	 *  What the timings have been put through to match the film.
	 * 
	 *  Carried so that the sync control opens on the value in force rather than
	 *  on nothing, and so that the player knows what the cues it was handed
	 *  have already had done to them.
	 */
	correction: CorrectionView,
};

/**  A film's picture. */
export type VideoView = {
	/**
	 *  What the codec is called, and what the file wrote where nothing here has
	 *  a name for it. Showing the identifier is more use than the word unknown.
	 */
	codec: string,
	width: number | null,
	height: number | null,
	bitDepth: number | null,
	frameRate: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

